# Sales Forecasting & Demand Prediction Analysis

## Notebook 01 — Data Inspection & Quality Validation

### Objective
Inspect the historical sales dataset, understand its structure,
validate data quality, and assess its suitability for forecasting.

### Dataset
- Source: Kaggle Store Item Demand Forecasting Challenge
- Total Records: 913,000
- Total Columns: 4
- Date Range: 2013-01-01 to 2017-12-31
- Stores: 10
- Items: 50

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
import os

file_path = "../data/raw/train.csv"
df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
print("Dataset Shape:", df.shape)
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Dataset Shape: (913000, 4)
Total Rows: 913000
Total Columns: 4

In [4]:
print("First 5 Records:")
display(df.head())

print("Last 5 Records:")
display(df.tail())

First 5 Records:

         date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

Last 5 Records:

              date  store  item  sales
912995  2017-12-27     10    50     63
912996  2017-12-28     10    50     59
912997  2017-12-29     10    50     74
912998  2017-12-30     10    50     62
912999  2017-12-31     10    50     82

In [5]:
print("Column Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Column Names:
['date', 'store', 'item', 'sales']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    913000 non-null  str
 1   store   913000 non-null  int64
 2   item    913000 non-null  int64
 3   sales   913000 non-null  int64
dtypes: int64(3), str(1)
memory usage: 27.9 MB

In [6]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Missing Values:
date     0
store    0
item     0
sales    0
dtype: int64

Duplicate Rows:
0

In [7]:
print("Minimum Date:", df["date"].min())
print("Maximum Date:", df["date"].max())

print("\nUnique Stores:", df["store"].nunique())
print("Unique Items:", df["item"].nunique())

print("\nSales Summary:")
print(df["sales"].describe())

Minimum Date: 2013-01-01
Maximum Date: 2017-12-31

Unique Stores: 10
Unique Items: 50

Sales Summary:
count    913000.000000
mean         52.250287
std          28.801144
min           0.000000
25%          30.000000
50%          47.000000
75%          70.000000
max         231.000000
Name: sales, dtype: float64

In [8]:
print("Negative Sales:", (df["sales"] < 0).sum())
print("Zero Sales:", (df["sales"] == 0).sum())

print("Minimum Sales:", df["sales"].min())
print("Maximum Sales:", df["sales"].max())

Negative Sales: 0
Zero Sales: 1
Minimum Sales: 0
Maximum Sales: 231

In [9]:
duplicate_keys = df.duplicated(
    subset=["date", "store", "item"]
).sum()

print("Duplicate Store-Item-Date Records:", duplicate_keys)

Duplicate Store-Item-Date Records: 0

In [10]:
parsed_dates = pd.to_datetime(
    df["date"],
    errors="coerce"
)

print("Invalid Dates:", parsed_dates.isna().sum())

print("Earliest Date:", parsed_dates.min())
print("Latest Date:", parsed_dates.max())

Invalid Dates: 0
Earliest Date: 2013-01-01 00:00:00
Latest Date: 2017-12-31 00:00:00

In [11]:
print("Store IDs:")
print(sorted(df["store"].unique()))

print("\nItem ID Range:")
print(df["item"].min(), "to", df["item"].max())

print("\nInvalid Store IDs:", (df["store"] <= 0).sum())
print("Invalid Item IDs:", (df["item"] <= 0).sum())

Store IDs:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]

Item ID Range:
1 to 50

Invalid Store IDs: 0
Invalid Item IDs: 0

total_days = (parsed_dates.max() - parsed_dates.min()).days + 1

expected_records = (
    total_days
    * df["store"].nunique()
    * df["item"].nunique()
)

print("Total Days:", total_days)
print("Expected Records:", expected_records)
print("Actual Records:", len(df))
print("Difference:", expected_records - len(df))

In [13]:
expected_dates = pd.date_range(
    start=parsed_dates.min(),
    end=parsed_dates.max(),
    freq="D"
)

actual_dates = pd.DatetimeIndex(parsed_dates.unique())

missing_dates = expected_dates.difference(actual_dates)

print("Missing Calendar Dates:", len(missing_dates))

store_item_counts = df.groupby(
    ["store", "item"]
)["date"].nunique()

print("Total Store-Item Combinations:", len(store_item_counts))

print(
    "Combinations with Incomplete Date Coverage:",
    (store_item_counts != len(expected_dates)).sum()
)

Missing Calendar Dates: 0
Total Store-Item Combinations: 500
Combinations with Incomplete Date Coverage: 0

## Data Quality Findings

### Dataset Overview
- 913,000 historical sales records.
- 4 columns: date, store, item, sales.
- 10 stores and 50 unique items.
- Daily sales data from 2013 through 2017.

### Quality Assessment
- No missing values.
- No exact duplicate rows.
- No duplicate store-item-date combinations.
- No negative sales.
- One zero-sales observation retained for further review.
- No invalid dates.
- No invalid store or item identifiers.
- Expected and actual record counts match.

### Data Preparation Requirements
1. Convert the date column to datetime.
2. Preserve the original dataset.
3. Create useful time-based features.
4. Aggregate sales at appropriate forecasting levels.
5. Prepare chronological training and testing datasets.

### Conclusion
The dataset passed the initial data quality checks
and is suitable for further sales analysis and forecasting.