# Sales Forecasting & Demand Prediction Analysis

## Notebook 02 — Data Cleaning & Transformation

### Objective
Prepare the historical sales dataset for exploratory
data analysis and demand forecasting.

### Planned Tasks
1. Load the original dataset.
2. Convert the date column to datetime.
3. Validate data types and sales quantities.
4. Create time-based features.
5. Prepare clean data for analysis.
6. Export the processed dataset.

### Data Integrity
The original dataset in data/raw/ will remain unchanged.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
file_path = Path("../data/raw/train.csv")

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset Shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset Shape: (913000, 4)

         date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [3]:
df_clean = df.copy()

print("Working copy created successfully!")
print("Original Shape:", df.shape)
print("Working Copy Shape:", df_clean.shape)

Working copy created successfully!
Original Shape: (913000, 4)
Working Copy Shape: (913000, 4)

In [4]:
print("Data Types Before Conversion:")
print(df_clean.dtypes)

Data Types Before Conversion:
date       str
store    int64
item     int64
sales    int64
dtype: object

In [5]:
df_clean["date"] = pd.to_datetime(
    df_clean["date"],
    format="%Y-%m-%d",
    errors="raise"
)

print("Date conversion completed successfully!")

Date conversion completed successfully!

In [6]:
print("Data Types After Conversion:")
print(df_clean.dtypes)

print("\nFirst 5 Records:")
display(df_clean.head())

Data Types After Conversion:
date     datetime64[us]
store             int64
item              int64
sales             int64
dtype: object

First 5 Records:

        date  store  item  sales
0 2013-01-01      1     1     13
1 2013-01-02      1     1     11
2 2013-01-03      1     1     14
3 2013-01-04      1     1     13
4 2013-01-05      1     1     10

In [7]:
print("Earliest Date:", df_clean["date"].min())
print("Latest Date:", df_clean["date"].max())

print("\nMissing Values After Conversion:")
print(df_clean.isnull().sum())

Earliest Date: 2013-01-01 00:00:00
Latest Date: 2017-12-31 00:00:00

Missing Values After Conversion:
date     0
store    0
item     0
sales    0
dtype: int64

In [8]:
print("Original Records:", len(df))
print("Cleaned Records:", len(df_clean))

print("\nDate Column Is Datetime:",
      pd.api.types.is_datetime64_any_dtype(df_clean["date"]))

print("Store Is Numeric:",
      pd.api.types.is_numeric_dtype(df_clean["store"]))

print("Item Is Numeric:",
      pd.api.types.is_numeric_dtype(df_clean["item"]))

print("Sales Is Numeric:",
      pd.api.types.is_numeric_dtype(df_clean["sales"]))

print("\nMissing Values:", df_clean.isnull().sum().sum())

Original Records: 913000
Cleaned Records: 913000

Date Column Is Datetime: True
Store Is Numeric: True
Item Is Numeric: True
Sales Is Numeric: True

Missing Values: 0

In [9]:
df_clean["Year"] = df_clean["date"].dt.year

print("Year column created successfully!")
print(df_clean["Year"].unique())

Year column created successfully!
[2013 2014 2015 2016 2017]

In [10]:
df_clean["Month"] = df_clean["date"].dt.month
df_clean["Quarter"] = df_clean["date"].dt.quarter

print("Month and Quarter columns created!")

display(
    df_clean[["date", "Month", "Quarter"]].head()
)

Month and Quarter columns created!

        date  Month  Quarter
0 2013-01-01      1        1
1 2013-01-02      1        1
2 2013-01-03      1        1
3 2013-01-04      1        1
4 2013-01-05      1        1

In [11]:
df_clean["Day"] = df_clean["date"].dt.day

df_clean["Day_of_Week"] = df_clean["date"].dt.day_of_week

print("Day and Day_of_Week columns created!")

display(
    df_clean[["date", "Day", "Day_of_Week"]].head()
)

Day and Day_of_Week columns created!

        date  Day  Day_of_Week
0 2013-01-01    1            1
1 2013-01-02    2            2
2 2013-01-03    3            3
3 2013-01-04    4            4
4 2013-01-05    5            5

In [12]:
df_clean["Is_Weekend"] = (
    df_clean["Day_of_Week"] >= 5
).astype(int)

print("Weekend indicator created!")

display(
    df_clean[
        ["date", "Day_of_Week", "Is_Weekend"]
    ].head(10)
)

Weekend indicator created!

        date  Day_of_Week  Is_Weekend
0 2013-01-01            1           0
1 2013-01-02            2           0
2 2013-01-03            3           0
3 2013-01-04            4           0
4 2013-01-05            5           1
5 2013-01-06            6           1
6 2013-01-07            0           0
7 2013-01-08            1           0
8 2013-01-09            2           0
9 2013-01-10            3           0

In [13]:
print("Dataset Shape:", df_clean.shape)

print("\nColumn Names:")
print(df_clean.columns.tolist())

print("\nData Types:")
print(df_clean.dtypes)

print("\nMissing Values:")
print(df_clean.isnull().sum())

print("\nFirst 5 Records:")
display(df_clean.head())

Dataset Shape: (913000, 10)

Column Names:
['date', 'store', 'item', 'sales', 'Year', 'Month', 'Quarter', 'Day', 'Day_of_Week', 'Is_Weekend']

Data Types:
date           datetime64[us]
store                   int64
item                    int64
sales                   int64
Year                    int32
Month                   int32
Quarter                 int32
Day                     int32
Day_of_Week             int32
Is_Weekend              int64
dtype: object

Missing Values:
date           0
store          0
item           0
sales          0
Year           0
Month          0
Quarter        0
Day            0
Day_of_Week    0
Is_Weekend     0
dtype: int64

First 5 Records:

,date,store,item,sales,Year,Month,Quarter,Day,Day_of_Week,Is_Weekend
0,2013-01-01,1,1,13,2013,1,1,1,1,0
1,2013-01-02,1,1,11,2013,1,1,2,2,0
2,2013-01-03,1,1,14,2013,1,1,3,3,0
3,2013-01-04,1,1,13,2013,1,1,4,4,0
4,2013-01-05,1,1,10,2013,1,1,5,5,1

In [14]:
# Step 4.4.1 - Final Data Validation

print("========== FINAL DATA VALIDATION ==========")

# 1. Check dataset shape
print("Dataset Shape:", df_clean.shape)

# 2. Check missing values
print("Total Missing Values:",
      df_clean.isnull().sum().sum())

# 3. Check duplicate business keys
print("Duplicate Store-Item-Date Records:",
      df_clean.duplicated(
          subset=["date", "store", "item"]
      ).sum())

# 4. Check negative sales
print("Negative Sales:",
      (df_clean["sales"] < 0).sum())

# 5. Check zero sales
print("Zero Sales:",
      (df_clean["sales"] == 0).sum())

# 6. Check date range
print("Earliest Date:", df_clean["date"].min())
print("Latest Date:", df_clean["date"].max())

# 7. Check unique stores and items
print("Unique Stores:", df_clean["store"].nunique())
print("Unique Items:", df_clean["item"].nunique())

# 8. Verify weekend indicator
expected_weekend = (
    df_clean["date"].dt.day_of_week >= 5
).astype(int)

print("Incorrect Weekend Indicators:",
      (df_clean["Is_Weekend"] != expected_weekend).sum())

print("========== VALIDATION COMPLETE ==========")

========== FINAL DATA VALIDATION ==========
Dataset Shape: (913000, 10)
Total Missing Values: 0
Duplicate Store-Item-Date Records: 0
Negative Sales: 0
Zero Sales: 1
Earliest Date: 2013-01-01 00:00:00
Latest Date: 2017-12-31 00:00:00
Unique Stores: 10
Unique Items: 50
Incorrect Weekend Indicators: 0
========== VALIDATION COMPLETE ==========

In [15]:
from pathlib import Path

# Define output location
output_path = Path("../data/processed/sales_cleaned.csv")

# Ensure output folder exists
output_path.parent.mkdir(parents=True, exist_ok=True)

# Export cleaned dataset
df_clean.to_csv(output_path, index=False)

print("Cleaned dataset exported successfully!")
print("Saved Location:", output_path.resolve())

Cleaned dataset exported successfully!
Saved Location: C:\Users\ANKIT TRIPATHI\Desktop\Sales-Forecasting-Demand-Prediction\data\processed\sales_cleaned.csv

In [16]:
# Reload exported data
df_exported = pd.read_csv(
    "../data/processed/sales_cleaned.csv",
    parse_dates=["date"]
)

print("Exported Dataset Shape:", df_exported.shape)

print("Missing Values:", df_exported.isnull().sum().sum())

print("Duplicate Business Keys:",
      df_exported.duplicated(
          subset=["date", "store", "item"]
      ).sum())

print("Date Data Type:", df_exported["date"].dtype)

print("\nFirst 5 Records:")
display(df_exported.head())

Exported Dataset Shape: (913000, 10)
Missing Values: 0
Duplicate Business Keys: 0
Date Data Type: datetime64[us]

First 5 Records:

,date,store,item,sales,Year,Month,Quarter,Day,Day_of_Week,Is_Weekend
0,2013-01-01,1,1,13,2013,1,1,1,1,0
1,2013-01-02,1,1,11,2013,1,1,2,2,0
2,2013-01-03,1,1,14,2013,1,1,3,3,0
3,2013-01-04,1,1,13,2013,1,1,4,4,0
4,2013-01-05,1,1,10,2013,1,1,5,5,1